name: Publish .NET App and Release

on:
  push:
    # Trigger on version tags like v1.0.0
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: windows-latest  # Only run on Windows

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET SDK (Latest)
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'  # Use the latest .NET 9 SDK

    - name: Restore dependencies
      run: dotnet restore ./GateEntry/GateEntry.csproj

    - name: Build project
      run: dotnet build ./GateEntry/GateEntry.csproj --configuration Release --no-restore

    - name: Publish application
      run: |
        dotnet publish ./GateEntry/GateEntry.csproj --configuration Release --output publish_output

    - name: Archive published output
      shell: pwsh
      run: |
        Compress-Archive -Path publish_output\* -DestinationPath app.zip -Force

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./app.zip
        asset_name: app.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
