name: .NET Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build and Release
    runs-on: windows-latest
    permissions:
      contents: write # 👈 Add this permission

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish .\GateEntry\GateEntry.csproj --configuration Release --runtime win-x64 --self-contained true --output ./publish
      # Replace "YourProjectName.csproj" with the actual path to your project file.

    - name: Zip the release
      run: |
        $releaseName = "GateEntry-${{ github.ref_name }}"
        Compress-Archive -Path ./publish\* -DestinationPath ./$gateentry.zip
        echo "RELEASE_NAME=$releaseName" >> $env:GITHUB_ENV
      # Replace "YourProjectName" with your desired release name prefix.

    - name: Create GitHub Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "${{ env.RELEASE_NAME }}.zip"
        token: ${{ secrets.GITHUB_TOKEN }}